# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks x
permalink:        pretty
relative_permalinks: true

# Setup
title:            HA
tagline:          'A Jekyll theme'
description:      Random insecure thoughts... 
url:              http://flatfly.github.io
baseurl:          /

author:
  name:           'Sven Faw'
  url:            https://twitter.com/hexatomium

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
