# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks x
permalink:        pretty
relative_permalinks: true

# Setup
title:            AK
tagline:          '@aok1425 blog'
description:      Will replace this with something interesting... 
url:              http://aok1425.github.io
baseurl:          /

author:
  name:           'Alexander Ko'
  url:            https://github.com/aok1425

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aok1425/aok1425.github.io
